# Generated by Django 4.0.3 on 2022-04-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='Enter the first name of figther', max_length=50, null=True)),
                ('nick_name', models.CharField(blank=True, help_text='Enter the nick name of figther', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, help_text='Enter the last name of figther', max_length=50, null=True)),
                ('date_of_birth', models.DateField()),
                ('height', models.CharField(blank=True, help_text='Enter the height of figther', max_length=10, null=True)),
                ('wieght', models.CharField(blank=True, help_text='Enter the wieght of figther', max_length=10, null=True)),
            ],
            options={
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('draws', models.IntegerField(blank=True, null=True)),
                ('fighter_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.fighter')),
            ],
            options={
                'ordering': ['-wins', '-losses'],
            },
        ),
    ]
